import type { CallRecord } from "@/types/call-record"

// Enhanced mock data with comprehensive next steps and customer call summaries
export const enhancedMockData = {
  // Call Records with detailed summaries and next steps
  callRecords: [
    {
      call_id: "call_2024_001_abc123",
      dealership_id: "dealer_001",
      started_at: "2024-01-15T14:30:00Z",
      ended_at: "2024-01-15T14:37:30Z",
      direction: "inbound" as const,
      domain: "sales" as const,
      campaign_id: null,
      customer: {
        name: "Manan Chawla",
        phone: "+15551234567",
        email: "sarah.johnson@email.com",
      },
      vehicle: {
        vin: "1HGBH41JXMN109186",
        stock_id: "STK001",
        year: 2022,
        make: "Honda",
        model: "Civic",
        trim: "EX",
        delivery_type: "self_drive",
      },
      primary_intent: "schedule_test_drive",
      intents: [
        { label: "schedule_test_drive", confidence: 0.95 },
        { label: "pricing_payment", confidence: 0.3 },
      ],
      outcome: "appointment_scheduled",
      appointment: {
        type: "test_drive" as const,
        starts_at: "2024-01-16T15:00:00Z",
        ends_at: "2024-01-16T15:30:00Z",
        location: "Main Showroom",
        advisor: "Mike Rodriguez",
        status: "scheduled" as const,
      },
      sentiment: {
        label: "positive" as const,
        score: 0.8,
      },
      ai_score: 8.5,
      containment: true,
      summary: "Customer called interested in test driving a 2022 Honda Civic EX. Successfully scheduled appointment for tomorrow at 3 PM with Mike Rodriguez. Customer mentioned they're looking to purchase within the next week and prefers automatic transmission. Showed strong interest in financing options and trade-in value for their 2019 Toyota Corolla.",
      notes: "Customer has excellent credit score (750+). Trade-in vehicle: 2019 Toyota Corolla LE with 45,000 miles. Prefers automatic transmission. Budget range: $25,000-$30,000. Very responsive to follow-up calls.",
      follow_up: {
        needed: true,
        reason: "Send test drive reminder and prepare financing options",
        due_at: "2024-01-16T14:00:00Z",
        assignee: "Mike Rodriguez",
      },
      metrics: {
        duration_sec: 450,
        hold_sec: 0,
        silence_sec: 15,
      },
      recording_url: "https://recordings.example.com/call_001.mp3",
      transcript_url: "https://transcripts.example.com/call_001.txt",
      tags: ["hot_lead", "test_drive", "financing_ready"],
    },
    {
      call_id: "call_2024_002_def456",
      dealership_id: "dealer_001",
      started_at: "2024-01-15T16:15:00Z",
      ended_at: "2024-01-15T16:22:15Z",
      direction: "inbound" as const,
      domain: "service" as const,
      campaign_id: null,
      customer: {
        name: "Robert Chen",
        phone: "+15559876543",
        email: null,
      },
      vehicle: {
        vin: "2T1BURHE0JC123456",
        stock_id: null,
        year: 2018,
        make: "Toyota",
        model: "Corolla",
        trim: "LE",
        delivery_type: "pickup",
      },
      primary_intent: "schedule_service",
      intents: [{ label: "schedule_service", confidence: 0.9 }],
      outcome: "appointment_scheduled",
      appointment: {
        type: "service" as const,
        starts_at: "2024-01-17T09:00:00Z",
        ends_at: "2024-01-17T11:00:00Z",
        location: "Service Bay 3",
        advisor: "Jennifer Walsh",
        status: "scheduled" as const,
      },
      sentiment: {
        label: "neutral" as const,
        score: 0.5,
      },
      ai_score: 7.8,
      containment: true,
      summary: "Customer called to schedule routine maintenance for 2018 Toyota Corolla LE. Booked oil change and inspection for Wednesday morning. Customer mentioned slight noise when braking and wants full diagnostic. Vehicle has 67,000 miles and is due for 60K service. Customer is loyal service customer with good payment history.",
      notes: "Customer mentioned slight noise when braking - advised to mention to technician. Vehicle due for 60K major service. Customer has extended warranty that may cover some costs. Previous service records show good maintenance history.",
      follow_up: {
        needed: true,
        reason: "Send service reminder and prepare diagnostic checklist",
        due_at: "2024-01-16T17:00:00Z",
        assignee: "Jennifer Walsh",
      },
      metrics: {
        duration_sec: 435,
        hold_sec: 30,
        silence_sec: 8,
      },
      recording_url: "https://recordings.example.com/call_002.mp3",
      transcript_url: "https://transcripts.example.com/call_002.txt",
      tags: ["routine_maintenance", "loyal_customer", "diagnostic_needed"],
    },
  ],

  // Analytics and Dashboard Metrics
  analytics: {
    callVolume: {
      daily: [45, 52, 38, 61, 49, 55, 42],
      weekly: [320, 285, 310, 295, 340, 315, 330],
      monthly: [1250, 1180, 1320, 1280, 1400, 1350],
    },
    conversionRates: {
      sales: 0.68,
      service: 0.82,
      finance: 0.74,
      overall: 0.75,
    },
    customerSatisfaction: {
      current: 4.6,
      previous: 4.4,
      trend: "up",
      responses: 156,
    },
    revenueMetrics: {
      sales: 2850000,
      service: 890000,
      finance: 420000,
      total: 4160000,
      growth: 0.12,
    },
    agentPerformance: [
      {
        name: "Mike Rodriguez",
        calls: 45,
        conversion: 0.78,
        satisfaction: 4.7,
        revenue: 125000,
      },
      {
        name: "Sarah Mitchell",
        calls: 52,
        conversion: 0.82,
        satisfaction: 4.8,
        revenue: 145000,
      },
      {
        name: "Tom Wilson",
        calls: 38,
        conversion: 0.71,
        satisfaction: 4.5,
        revenue: 98000,
      },
      {
        name: "Jennifer Walsh",
        calls: 41,
        conversion: 0.85,
        satisfaction: 4.6,
        revenue: 112000,
      },
      {
        name: "Carlos Martinez",
        calls: 35,
        conversion: 0.79,
        satisfaction: 4.7,
        revenue: 89000,
      },
    ],
    topVehicles: [
      { make: "Honda", model: "Civic", interest: 0.28, testDrives: 45 },
      { make: "Toyota", model: "Camry", interest: 0.25, testDrives: 38 },
      { make: "Ford", model: "F-150", interest: 0.22, testDrives: 32 },
      { make: "Hyundai", model: "Tucson", interest: 0.18, testDrives: 28 },
      { make: "Volkswagen", model: "Jetta", interest: 0.15, testDrives: 25 },
    ],
    serviceMetrics: {
      appointments: 89,
      completed: 76,
      revenue: 89000,
      averageTicket: 1171,
      customerRetention: 0.88,
    },
    salesMetrics: {
      leads: 156,
      testDrives: 89,
      sales: 67,
      conversionRate: 0.43,
      averageSalePrice: 42500,
    },
  },

  // Follow-up Tasks and Next Steps
  followUpTasks: [
    {
      id: "task_001",
      type: "call_back",
      customer: "Manan Chawla",
      vehicle: "2022 Honda Civic EX",
      dueDate: "2024-01-16T14:00:00Z",
      assignee: "Mike Rodriguez",
      priority: "high",
      notes: "Send test drive reminder and prepare financing options",
      status: "pending",
    },
    {
      id: "task_002",
      type: "service_reminder",
      customer: "Robert Chen",
      vehicle: "2018 Toyota Corolla LE",
      dueDate: "2024-01-16T17:00:00Z",
      assignee: "Jennifer Walsh",
      priority: "medium",
      notes: "Send service reminder and prepare diagnostic checklist",
      status: "pending",
    },
    {
      id: "task_003",
      type: "appointment_reminder",
      customer: "Maria Garcia",
      vehicle: "2023 Ford F-150 XLT",
      dueDate: "2024-01-18T13:00:00Z",
      assignee: "Tom Wilson",
      priority: "high",
      notes: "Send reminder 1 hour before appointment and prepare both engine options",
      status: "pending",
    },
    {
      id: "task_004",
      type: "sales_callback",
      customer: "David Thompson",
      vehicle: "2021 VW Golf SE",
      dueDate: "2024-01-15T16:00:00Z",
      assignee: "Sales Manager",
      priority: "urgent",
      notes: "Sales manager callback required for competitive pricing",
      status: "pending",
    },
    {
      id: "task_005",
      type: "service_followup",
      customer: "Anonymous",
      vehicle: "2015 Ford Fusion SE",
      dueDate: "2024-01-18T10:00:00Z",
      assignee: "Service Team",
      priority: "low",
      notes: "Follow-up call to check if customer needs additional parts or service",
      status: "pending",
    },
  ],

  // Recent Activity Feed
  recentActivity: [
    {
      id: "activity_001",
      type: "appointment_scheduled",
      customer: "Lisa Anderson",
      vehicle: "2023 Hyundai Tucson Limited",
      timestamp: "2024-01-15T17:42:15Z",
      agent: "Sarah Mitchell",
      details: "Test drive scheduled for tomorrow morning",
    },
    {
      id: "activity_002",
      type: "service_completed",
      customer: "Michael Brown",
      vehicle: "2019 Toyota Camry XLE",
      timestamp: "2024-01-15T16:30:00Z",
      agent: "Jennifer Walsh",
      details: "Oil change and inspection completed",
    },
    {
      id: "activity_003",
      type: "sale_closed",
      customer: "Lisa Wilson",
      vehicle: "2023 Nissan Altima",
      timestamp: "2024-01-15T16:00:00Z",
      agent: "Mike Rodriguez",
      details: "Vehicle sold with extended warranty",
    },
    {
      id: "activity_004",
      type: "follow_up_scheduled",
      customer: "Jennifer Lee",
      vehicle: "2022 VW Jetta SEL",
      timestamp: "2024-01-15T16:52:15Z",
      agent: "Sales Team",
      details: "Competitive pricing follow-up scheduled",
    },
    {
      id: "activity_005",
      type: "warranty_escalation",
      customer: "Anonymous",
      vehicle: "2016 Ford Fusion Titanium",
      timestamp: "2024-01-15T11:25:40Z",
      agent: "Warranty Specialist",
      details: "Transmission warranty coverage verification needed",
    },
  ],

  // Customer Insights and Demographics
  customerInsights: {
    demographics: {
      ageGroups: {
        "18-25": 0.12,
        "26-35": 0.28,
        "36-45": 0.32,
        "46-55": 0.18,
        "55+": 0.10,
      },
      incomeLevels: {
        "Under $50K": 0.15,
        "$50K-$75K": 0.25,
        "$75K-$100K": 0.35,
        "$100K-$150K": 0.20,
        "$150K+": 0.05,
      },
    },
    preferences: {
      communicationMethod: {
        phone: 0.45,
        email: 0.35,
        sms: 0.20,
      },
      vehicleTypes: {
        sedan: 0.35,
        suv: 0.40,
        truck: 0.15,
        hybrid: 0.10,
      },
      serviceIntervals: {
        "Every 3 months": 0.25,
        "Every 6 months": 0.45,
        "Annually": 0.20,
        "As needed": 0.10,
      },
    },
    satisfactionDrivers: {
      "Service Quality": 4.7,
      "Communication": 4.5,
      "Timeliness": 4.6,
      "Price": 4.3,
      "Vehicle Selection": 4.8,
    },
  },

  // Market Trends and Inventory
  marketTrends: {
    inventory: {
      total: 156,
      new: 89,
      used: 67,
      popularMakes: ["Honda", "Toyota", "Ford", "Hyundai", "Volkswagen"],
    },
    pricing: {
      averageNew: 38500,
      averageUsed: 24500,
      marketTrend: "stable",
      competitivePosition: "competitive",
    },
    demand: {
      trendingUp: ["Hybrids", "SUVs", "Trucks"],
      trendingDown: ["Sedans", "Luxury"],
      seasonalFactors: "winter_prep",
    },
  },

  // Quick Stats for Dashboard Cards
  quickStats: {
    totalCalls: 156,
    activeAppointments: 23,
    pendingFollowUps: 18,
    todayRevenue: 45000,
    customerSatisfaction: 4.6,
    conversionRate: 0.75,
    averageCallDuration: "6m 23s",
    topPerformingAgent: "Sarah Mitchell",
  },
}
