import type { CallRecord } from "@/types/call-record"

export const mockCallRecords: CallRecord[] = [
  {
    call_id: "call_2024_001_abc123",
    dealership_id: "dealer_001",
    started_at: "2024-01-15T14:30:00Z",
    ended_at: "2024-01-15T14:37:30Z",
    direction: "inbound",
    domain: "sales",
    campaign_id: null,
    customer: {
      name: "Manan Chawla",
      phone: "+1 (555) 123-4567",
      email: "sarah.johnson@email.com",
    },
    vehicle: {
      vin: "1HGBH41JXMN109186",
      stock_id: "STK001",
      year: 2022,
      make: "Honda",
      model: "Civic",
      trim: "EX",
      delivery_type: "self_drive",
    },
    primary_intent: "schedule_test_drive",
    intents: [
      { label: "schedule_test_drive", confidence: 0.95 },
      { label: "pricing_payment", confidence: 0.3 },
    ],
    outcome: "appointment_scheduled",
    appointment: {
      type: "test_drive",
      starts_at: "2024-01-16T15:00:00Z",
      ends_at: "2024-01-16T15:30:00Z",
      location: "Main Showroom",
      advisor: "Mike Rodriguez",
      status: "scheduled",
    },
    sentiment: {
      label: "positive",
      score: 0.8,
    },
    ai_score: 8.5,
    containment: true,
    summary:
      "Customer called interested in test driving a 2022 Honda Civic EX. Successfully scheduled appointment for tomorrow at 3 PM with Mike Rodriguez. Customer mentioned they're looking to purchase within the next week and prefers automatic transmission. Showed strong interest in financing options and trade-in value for their 2019 Toyota Corolla.",
    notes: "Customer has excellent credit score (750+). Trade-in vehicle: 2019 Toyota Corolla LE with 45,000 miles. Prefers automatic transmission. Budget range: $25,000-$30,000. Very responsive to follow-up calls.",
    follow_up: {
      needed: true,
      reason: "Send test drive reminder and prepare financing options",
      due_at: "2024-01-16T14:00:00Z",
      assignee: "Mike Rodriguez",
    },
    metrics: {
      duration_sec: 450,
      hold_sec: 0,
      silence_sec: 15,
    },
    recording_url: "https://recordings.example.com/call_001.mp3",
    voice_recording_url: "https://www.soundjay.com/misc/sounds/bell-ringing-05.wav",
    transcript_url: "https://transcripts.example.com/call_001.txt",
    tags: ["hot_lead", "test_drive", "financing_ready"],
  },
  {
    call_id: "call_2024_002_def456",
    dealership_id: "dealer_001",
    started_at: "2024-01-15T16:15:00Z",
    ended_at: "2024-01-15T16:22:15Z",
    direction: "inbound",
    domain: "service",
    campaign_id: null,
    customer: {
      name: "Robert Chen",
      phone: "+1 (555) 987-6543",
      email: null,
    },
    vehicle: {
      vin: "2T1BURHE0JC123456",
      stock_id: null,
      year: 2018,
      make: "Toyota",
      model: "Corolla",
      trim: "LE",
      delivery_type: "pickup",
    },
    primary_intent: "schedule_service",
    intents: [{ label: "schedule_service", confidence: 0.9 }],
    outcome: "appointment_scheduled",
    appointment: {
      type: "service",
      starts_at: "2024-01-17T09:00:00Z",
      ends_at: "2024-01-17T11:00:00Z",
      location: "Service Bay 3",
      advisor: "Jennifer Walsh",
      status: "scheduled",
    },
    sentiment: {
      label: "neutral",
      score: 0.5,
    },
    ai_score: 7.8,
    containment: true,
    summary:
      "Customer called to schedule routine maintenance for 2018 Toyota Corolla LE. Booked oil change and inspection for Wednesday morning. Customer mentioned slight noise when braking and wants full diagnostic. Vehicle has 67,000 miles and is due for 60K service. Customer is loyal service customer with good payment history.",
    notes: "Customer mentioned slight noise when braking - advised to mention to technician. Vehicle due for 60K major service. Customer has extended warranty that may cover some costs. Previous service records show good maintenance history.",
    follow_up: {
      needed: true,
      reason: "Send service reminder and prepare diagnostic checklist",
      due_at: "2024-01-16T17:00:00Z",
      assignee: "Jennifer Walsh",
    },
    metrics: {
      duration_sec: 435,
      hold_sec: 30,
      silence_sec: 8,
    },
    recording_url: "https://recordings.example.com/call_002.mp3",
    voice_recording_url: "https://www.soundjay.com/misc/sounds/bell-ringing-05.wav",
    transcript_url: "https://transcripts.example.com/call_002.txt",
    tags: ["routine_maintenance", "loyal_customer", "diagnostic_needed"],
  },
  {
    call_id: "call_2024_003_ghi789",
    dealership_id: "dealer_001",
    started_at: "2024-01-15T11:45:00Z",
    ended_at: "2024-01-15T11:52:30Z",
    direction: "outbound",
    domain: "sales",
    campaign_id: "campaign_follow_up_001",
    customer: {
      name: "Maria Garcia",
      phone: "+1 (555) 555-1234",
      email: "maria.garcia@email.com",
    },
    vehicle: {
      vin: null,
      stock_id: "STK045",
      year: 2023,
      make: "Ford",
      model: "F-150",
      trim: "XLT",
      delivery_type: "self_drive",
    },
    primary_intent: "appointment_confirmation",
    intents: [{ label: "appointment_confirmation", confidence: 0.85 }],
    outcome: "appointment_rescheduled",
    appointment: {
      type: "test_drive",
      starts_at: "2024-01-18T14:00:00Z",
      ends_at: "2024-01-18T14:30:00Z",
      location: "Main Showroom",
      advisor: "Tom Wilson",
      status: "rescheduled",
    },
    sentiment: {
      label: "positive",
      score: 0.7,
    },
    ai_score: 6.9,
    containment: true,
    summary:
      "Called to confirm tomorrow's test drive appointment for 2023 Ford F-150 XLT. Customer needed to reschedule to Thursday due to work conflict. Customer still very interested and confirmed financing pre-approval is ready. Discussed trade-in value for 2020 Honda CR-V. Customer wants to test both 2.7L and 3.5L engine options.",
    notes: "Customer still very interested. Confirmed financing pre-approval is ready. Trade-in: 2020 Honda CR-V EX-L with 38,000 miles. Customer prefers 4x4 option and towing package. Very responsive to follow-up.",
    follow_up: {
      needed: true,
      reason: "Send reminder 1 hour before appointment and prepare both engine options",
      due_at: "2024-01-18T13:00:00Z",
      assignee: "Tom Wilson",
    },
    metrics: {
      duration_sec: 450,
      hold_sec: 0,
      silence_sec: 12,
    },
    recording_url: "https://recordings.example.com/call_003.mp3",
    voice_recording_url: "https://www.soundjay.com/misc/sounds/bell-ringing-05.wav",
    transcript_url: "https://transcripts.example.com/call_003.txt",
    tags: ["reschedule", "hot_lead", "truck_interest", "financing_ready"],
  },
  {
    call_id: "call_2024_004_jkl012",
    dealership_id: "dealer_001",
    started_at: "2024-01-15T09:20:00Z",
    ended_at: "2024-01-15T09:35:45Z",
    direction: "inbound",
    domain: "sales",
    campaign_id: null,
    customer: {
      name: "David Thompson",
      phone: "+1 (555) 123-7890",
      email: "david.t@email.com",
    },
    vehicle: {
      vin: "3VWDX7AJ5DM123456",
      stock_id: "STK078",
      year: 2021,
      make: "Volkswagen",
      model: "Golf",
      trim: "SE",
      delivery_type: "pickup",
    },
    primary_intent: "pricing_inquiry",
    intents: [
      { label: "pricing_inquiry", confidence: 0.92 },
      { label: "financing_question", confidence: 0.7 },
    ],
    outcome: "transferred_to_human",
    appointment: null,
    sentiment: {
      label: "negative",
      score: 0.2,
    },
    ai_score: 4.2,
    containment: false,
    summary:
      "Customer called about 2021 VW Golf SE pricing and became frustrated with automated responses. Requested human agent for detailed pricing, financing options, and trade-in value. Customer has 2018 Honda Civic with 52,000 miles for trade-in. Budget range: $22,000-$28,000. Customer mentioned they're comparing with 3 other dealerships.",
    notes: "Customer has trade-in vehicle: 2018 Honda Civic LX with 52,000 miles. Needs financing options. Very price-sensitive and comparing with competitors. Escalated to sales manager for immediate attention. Customer has good credit but wants best possible rate.",
    follow_up: {
      needed: true,
      reason: "Sales manager callback required for competitive pricing",
      due_at: "2024-01-15T16:00:00Z",
      assignee: "Sales Manager",
    },
    metrics: {
      duration_sec: 945,
      hold_sec: 120,
      silence_sec: 45,
    },
    recording_url: "https://recordings.example.com/call_004.mp3",
    transcript_url: "https://transcripts.example.com/call_004.txt",
    tags: ["escalation", "pricing_inquiry", "competitive", "trade_in"],
  },
  {
    call_id: "call_2024_005_mno345",
    dealership_id: "dealer_001",
    started_at: "2024-01-15T13:10:00Z",
    ended_at: "2024-01-15T13:15:20Z",
    direction: "inbound",
    domain: "service",
    campaign_id: null,
    customer: {
      name: null,
      phone: "+1 (555) 987-1234",
      email: null,
    },
    vehicle: {
      vin: "1FADP3F22FL123456",
      stock_id: null,
      year: 2015,
      make: "Ford",
      model: "Fusion",
      trim: "SE",
      delivery_type: null,
    },
    primary_intent: "parts_inquiry",
    intents: [{ label: "parts_inquiry", confidence: 0.88 }],
    outcome: "info_provided",
    appointment: null,
    sentiment: {
      label: "neutral",
      score: 0.6,
    },
    ai_score: 8.9,
    containment: true,
    summary:
      "Customer inquired about brake pad replacement for 2015 Ford Fusion SE. Provided pricing and availability information. Customer will call back to schedule when ready. Parts are in stock and customer was satisfied with pricing. Vehicle has 89,000 miles and customer mentioned they're doing the work themselves.",
    notes: "Customer will call back to schedule when ready. Parts in stock. Customer doing DIY work. May need additional parts (rotors, calipers) once they start. Good opportunity for future service business.",
    follow_up: {
      needed: true,
      reason: "Follow-up call to check if customer needs additional parts or service",
      due_at: "2024-01-18T10:00:00Z",
      assignee: "Service Team",
    },
    metrics: {
      duration_sec: 320,
      hold_sec: 0,
      silence_sec: 5,
    },
    recording_url: "https://recordings.example.com/call_005.mp3",
    transcript_url: "https://transcripts.example.com/call_005.txt",
    tags: ["parts", "quick_inquiry", "diy_customer", "future_service"],
  },
  {
    call_id: "call_2024_006_pqr678",
    dealership_id: "dealer_001",
    started_at: "2024-01-15T17:30:00Z",
    ended_at: "2024-01-15T17:42:15Z",
    direction: "inbound",
    domain: "sales",
    campaign_id: null,
    customer: {
      name: "Lisa Anderson",
      phone: "+1 (555) 123-4567",
      email: "lisa.anderson@email.com",
    },
    vehicle: {
      vin: "5NPE34AF5FH123456",
      stock_id: "STK123",
      year: 2023,
      make: "Hyundai",
      model: "Tucson",
      trim: "Limited",
      delivery_type: "self_drive",
    },
    primary_intent: "schedule_test_drive",
    intents: [
      { label: "schedule_test_drive", confidence: 0.95 },
      { label: "warranty_question", confidence: 0.6 },
    ],
    outcome: "appointment_scheduled",
    appointment: {
      type: "test_drive",
      starts_at: "2024-01-16T10:00:00Z",
      ends_at: "2024-01-16T10:30:00Z",
      location: "Main Showroom",
      advisor: "Sarah Mitchell",
      status: "scheduled",
    },
    sentiment: {
      label: "positive",
      score: 0.9,
    },
    ai_score: 9.1,
    containment: true,
    summary:
      "Customer interested in 2023 Hyundai Tucson Limited. Successfully scheduled test drive for tomorrow morning. Customer has excellent credit score and is very interested in hybrid option. Currently drives 2020 Honda CR-V and wants to upgrade to something more fuel-efficient. Customer mentioned they're looking to purchase within 2 weeks.",
    notes: "Customer has excellent credit score (780+). Very interested in hybrid option. Currently drives 2020 Honda CR-V with 41,000 miles. Budget range: $35,000-$42,000. Wants to test both hybrid and gas models. Very responsive and ready to buy.",
    follow_up: {
      needed: true,
      reason: "Prepare both hybrid and gas models for test drive",
      due_at: "2024-01-16T09:00:00Z",
      assignee: "Sarah Mitchell",
    },
    metrics: {
      duration_sec: 735,
      hold_sec: 15,
      silence_sec: 8,
    },
    recording_url: "https://recordings.example.com/call_006.mp3",
    voice_recording_url: "https://www.soundjay.com/misc/sounds/bell-ringing-05.wav",
    transcript_url: "https://transcripts.example.com/call_006.txt",

    tags: ["hot_lead", "hybrid_interest", "upgrade_customer", "ready_to_buy"],
  },
  {
    call_id: "call_2024_007_stu901",
    dealership_id: "dealer_001",
    started_at: "2024-01-15T10:45:00Z",
    ended_at: "2024-01-15T10:50:30Z",
    direction: "inbound",
    domain: "service",
    campaign_id: null,
    customer: {
      name: "James Wilson",
      phone: "+1 (555) 987-6543",
      email: "james.w@email.com",
    },
    vehicle: {
      vin: "1G1ZT51806F123456",
      stock_id: null,
      year: 2006,
      make: "Chevrolet",
      model: "Cobalt",
      trim: "LT",
      delivery_type: "pickup",
    },
    primary_intent: "service_complaint",
    intents: [
      { label: "service_complaint", confidence: 0.94 },
      { label: "warranty_claim", confidence: 0.8 },
    ],
    outcome: "transferred_to_human",
    appointment: null,
    sentiment: {
      label: "negative",
      score: 0.1,
    },
    ai_score: 3.8,
    containment: false,
    summary:
      "Customer called with complaint about previous service. Engine light came back on after repair 2 weeks ago. Customer very upset and wants immediate resolution. Previous repair was catalytic converter replacement under warranty. Customer mentioned they've been without their car for 3 weeks total and need it for work. Escalated to service manager for immediate attention.",
    notes: "Customer very upset. Previous repair was 2 weeks ago. Warranty claim may be needed. Customer has been without car for 3 weeks total. Needs immediate resolution for work. Previous service advisor was John Smith. Customer wants compensation for inconvenience.",
    follow_up: {
      needed: true,
      reason: "Service manager investigation required - urgent customer satisfaction issue",
      due_at: "2024-01-15T14:00:00Z",
      assignee: "Service Manager",
    },
    metrics: {
      duration_sec: 330,
      hold_sec: 60,
      silence_sec: 20,
    },
    recording_url: "https://recordings.example.com/call_007.mp3",
    transcript_url: "https://transcripts.example.com/call_007.txt",
    tags: ["complaint", "warranty_issue", "urgent", "customer_satisfaction"],
  },
  {
    call_id: "call_2024_008_vwx234",
    dealership_id: "dealer_001",
    started_at: "2024-01-15T15:20:00Z",
    ended_at: "2024-01-15T15:25:45Z",
    direction: "inbound",
    domain: "sales",
    campaign_id: null,
    customer: {
      name: null,
      phone: "+1 (555) 123-7890",
      email: null,
    },
    vehicle: {
      vin: null,
      stock_id: null,
      year: 0,
      make: null,
      model: null,
      trim: null,
      delivery_type: null,
    },
    primary_intent: "general_inquiry",
    intents: [{ label: "general_inquiry", confidence: 0.75 }],
    outcome: "info_provided",
    appointment: null,
    sentiment: {
      label: "neutral",
      score: 0.5,
    },
    ai_score: 7.5,
    containment: true,
    summary:
      "Customer called to ask about dealership hours and location. Provided basic information about services offered. Customer is new to the area and just moved from California. They're looking for a reliable dealership for their family's vehicles. Customer mentioned they have a 2019 Toyota Highlander and 2021 Honda Civic. Very polite and appreciative of the information.",
    notes: "New customer to area. May return for future needs. Has 2019 Toyota Highlander and 2021 Honda Civic. Family-oriented customer. Good opportunity for future service and sales. Customer mentioned they'll be in the market for a new vehicle in 6-12 months.",
    follow_up: {
      needed: true,
      reason: "Welcome package and service reminder for existing vehicles",
      due_at: "2024-01-18T10:00:00Z",
      assignee: "Customer Service",
    },
    metrics: {
      duration_sec: 345,
      hold_sec: 0,
      silence_sec: 10,
    },
    recording_url: "https://recordings.example.com/call_008.mp3",
    transcript_url: "https://transcripts.example.com/call_008.txt",
    tags: ["new_customer", "general_info", "family_customer", "future_potential"],
  },
  {
    call_id: "call_2024_009_yza567",
    dealership_id: "dealer_001",
    started_at: "2024-01-15T12:30:00Z",
    ended_at: "2024-01-15T12:38:20Z",
    direction: "inbound",
    domain: "sales",
    campaign_id: null,
    customer: {
      name: "Amanda Rodriguez",
      phone: "+1 (555) 123-4567",
      email: "amanda.r@email.com",
    },
    vehicle: {
      vin: "1HGBH41JXMN109187",
      stock_id: "STK089",
      year: 2020,
      make: "Honda",
      model: "Accord",
      trim: "Sport",
      delivery_type: "self_drive",
    },
    primary_intent: "financing_application",
    intents: [
      { label: "financing_application", confidence: 0.91 },
      { label: "payment_calculation", confidence: 0.7 },
    ],
    outcome: "appointment_scheduled",
    appointment: {
      type: "test_drive",
      starts_at: "2024-01-16T13:00:00Z",
      ends_at: "2024-01-16T14:00:00Z",
      location: "Finance Office",
      advisor: "Carlos Martinez",
      status: "scheduled",
    },
    sentiment: {
      label: "positive",
      score: 0.8,
    },
    ai_score: 8.7,
    containment: true,
    summary:
      "Customer applied for financing on 2020 Honda Accord Sport. Pre-approved and scheduled finance meeting for tomorrow. Customer has excellent credit history (820 score) and down payment ready. Currently drives 2017 Honda Civic and wants to upgrade. Customer mentioned they want to keep payments under $400/month and prefer 60-month term. Very organized and prepared for the process.",
    notes: "Customer has good credit history (820 score). Down payment ready ($8,000). Currently drives 2017 Honda Civic with 65,000 miles. Wants payments under $400/month. Prefers 60-month term. Very organized and prepared. Good candidate for extended warranty and GAP coverage.",
    follow_up: {
      needed: true,
      reason: "Prepare financing documents and extended warranty options",
      due_at: "2024-01-16T12:00:00Z",
      assignee: "Carlos Martinez",
    },
    metrics: {
      duration_sec: 500,
      hold_sec: 45,
      silence_sec: 12,
    },
    recording_url: "https://recordings.example.com/call_009.mp3",
    voice_recording_url: "https://www.soundjay.com/misc/sounds/bell-ringing-05.wav",
    transcript_url: "https://transcripts.example.com/call_009.txt",
    tags: ["finance_approved", "ready_to_buy", "excellent_credit", "upgrade_customer"],
  },
  {
    call_id: "call_2024_010_bcd890",
    dealership_id: "dealer_001",
    started_at: "2024-01-15T14:15:00Z",
    ended_at: "2024-01-15T14:18:30Z",
    direction: "inbound",
    domain: "service",
    campaign_id: null,
    customer: {
      name: "Michael Brown",
      phone: "+1 (555) 987-6543",
      email: null,
    },
    vehicle: {
      vin: "2T1BURHE0JC123457",
      stock_id: null,
      year: 2019,
      make: "Toyota",
      model: "Camry",
      trim: "XLE",
      delivery_type: "pickup",
    },
    primary_intent: "schedule_service",
    intents: [{ label: "schedule_service", confidence: 0.89 }],
    outcome: "appointment_scheduled",
    appointment: {
      type: "service",
      starts_at: "2024-01-17T14:00:00Z",
      ends_at: "2024-01-17T15:30:00Z",
      location: "Service Bay 5",
      advisor: "Jennifer Walsh",
      status: "scheduled",
    },
    sentiment: {
      label: "positive",
      score: 0.7,
    },
    ai_score: 8.2,
    containment: true,
    summary:
      "Customer scheduled oil change and tire rotation for 2019 Toyota Camry XLE. Appointment set for Wednesday afternoon. Customer mentioned slight vibration at highway speeds and wants full diagnostic. Vehicle has 58,000 miles and is due for 60K service. Customer is loyal service customer with good payment history. Very satisfied with previous service experiences.",
    notes: "Customer mentioned slight vibration at highway speeds. Vehicle due for 60K major service. Customer has extended warranty that may cover some costs. Previous service records show good maintenance history. Customer very satisfied with service quality.",
    follow_up: {
      needed: true,
      reason: "Send service reminder and prepare diagnostic checklist",
      due_at: "2024-01-16T17:00:00Z",
      assignee: "Jennifer Walsh",
    },
    metrics: {
      duration_sec: 210,
      hold_sec: 0,
      silence_sec: 5,
    },
    recording_url: "https://recordings.example.com/call_010.mp3",
    transcript_url: "https://transcripts.example.com/call_010.txt",
    tags: ["routine_maintenance", "loyal_customer", "diagnostic_needed", "vibration_issue"],
  },
  {
    call_id: "call_2024_011_efg123",
    dealership_id: "dealer_001",
    started_at: "2024-01-15T16:45:00Z",
    ended_at: "2024-01-15T16:52:15Z",
    direction: "inbound",
    domain: "sales",
    campaign_id: null,
    customer: {
      name: "Jennifer Lee",
      phone: "+1 (555) 123-7890",
      email: "jennifer.lee@email.com",
    },
    vehicle: {
      vin: "3VWDX7AJ5DM123457",
      stock_id: "STK156",
      year: 2022,
      make: "Volkswagen",
      model: "Jetta",
      trim: "SEL",
      delivery_type: "self_drive",
    },
    primary_intent: "pricing_inquiry",
    intents: [
      { label: "pricing_inquiry", confidence: 0.93 },
      { label: "trade_in_question", confidence: 0.8 },
    ],
    outcome: "info_provided",
    appointment: null,
    sentiment: {
      label: "neutral",
      score: 0.6,
    },
    ai_score: 7.9,
    containment: true,
    summary:
      "Customer inquired about 2022 VW Jetta SEL pricing and trade-in value for 2018 Honda Civic. Provided detailed information about pricing, features, and financing options. Customer will compare with other dealerships and mentioned they're looking for the best overall value. Customer has good credit and is ready to buy within the next month. Trade-in vehicle is in excellent condition.",
    notes: "Customer will compare with other dealerships. Follow-up call scheduled for next week. Trade-in: 2018 Honda Civic EX with 42,000 miles in excellent condition. Customer has good credit (720+). Looking for best overall value, not just lowest price. Very thorough in research.",
    follow_up: {
      needed: true,
      reason: "Competitive pricing follow-up and additional incentives",
      due_at: "2024-01-22T10:00:00Z",
      assignee: "Sales Team",
    },
    metrics: {
      duration_sec: 435,
      hold_sec: 30,
      silence_sec: 15,
    },
    recording_url: "https://recordings.example.com/call_011.mp3",
    transcript_url: "https://transcripts.example.com/call_011.txt",
    tags: ["pricing_inquiry", "trade_in", "competitive", "thorough_research"],
  },
  {
    call_id: "call_2024_012_hij456",
    dealership_id: "dealer_001",
    started_at: "2024-01-15T11:20:00Z",
    ended_at: "2024-01-15T11:25:40Z",
    direction: "inbound",
    domain: "service",
    campaign_id: null,
    customer: {
      name: null,
      phone: "+1 (555) 987-1234",
      email: null,
    },
    vehicle: {
      vin: "1FADP3F22FL123457",
      stock_id: null,
      year: 2016,
      make: "Ford",
      model: "Fusion",
      trim: "Titanium",
      delivery_type: "pickup",
    },
    primary_intent: "warranty_question",
    intents: [{ label: "warranty_question", confidence: 0.87 }],
    outcome: "transferred_to_human",
    appointment: null,
    sentiment: {
      label: "negative",
      score: 0.3,
    },
    ai_score: 5.1,
    containment: false,
    summary:
      "Customer called about warranty coverage for transmission issue on 2016 Ford Fusion Titanium. Complex warranty question required human assistance. Customer has extended warranty through third-party provider. Vehicle has 78,000 miles and transmission is making grinding noises. Customer needs specific coverage details and wants to know if repair will be covered. Escalated to warranty specialist.",
    notes: "Customer has extended warranty through third-party provider. Specific coverage details needed. Vehicle has 78,000 miles. Transmission making grinding noises. Customer wants to know if repair will be covered before proceeding. Complex warranty situation.",
    follow_up: {
      needed: true,
      reason: "Warranty specialist callback for coverage verification",
      due_at: "2024-01-15T15:00:00Z",
      assignee: "Warranty Specialist",
    },
    metrics: {
      duration_sec: 340,
      hold_sec: 90,
      silence_sec: 25,
    },
    recording_url: "https://recordings.example.com/call_012.mp3",
    transcript_url: "https://transcripts.example.com/call_012.txt",
    tags: ["warranty", "transmission_issue", "escalation", "third_party_warranty"],
  },
  {
    call_id: "call_2024_013_klm789",
    dealership_id: "dealer_001",
    started_at: "2024-01-15T13:50:00Z",
    ended_at: "2024-01-15T13:58:30Z",
    direction: "inbound",
    domain: "sales",
    campaign_id: null,
    customer: {
      name: "Thomas Davis",
      phone: "+1 (555) 123-4567",
      email: "thomas.davis@email.com",
    },
    vehicle: {
      vin: "5NPE34AF5FH123458",
      stock_id: "STK234",
      year: 2023,
      make: "Hyundai",
      model: "Santa Fe",
      trim: "Calligraphy",
      delivery_type: "self_drive",
    },
    primary_intent: "schedule_test_drive",
    intents: [
      { label: "schedule_test_drive", confidence: 0.96 },
      { label: "financing_question", confidence: 0.7 },
    ],
    outcome: "appointment_scheduled",
    appointment: {
      type: "test_drive",
      starts_at: "2024-01-16T16:00:00Z",
      ends_at: "2024-01-16T16:30:00Z",
      location: "Main Showroom",
      advisor: "Sarah Mitchell",
      status: "scheduled",
    },
    sentiment: {
      label: "positive",
      score: 0.9,
    },
    ai_score: 9.3,
    containment: true,
    summary:
      "Customer interested in 2023 Hyundai Santa Fe Calligraphy. Successfully scheduled test drive for tomorrow afternoon. Customer has pre-approval from bank and is very interested in premium features. Currently drives 2020 Honda Pilot and wants to upgrade to something more luxurious. Customer mentioned they're looking to purchase within the next 2 weeks and has excellent credit score.",
    notes: "Customer has pre-approval from bank. Very interested in premium features. Currently drives 2020 Honda Pilot with 35,000 miles. Budget range: $45,000-$55,000. Excellent credit score (800+). Wants to test all premium features. Very responsive and ready to buy.",
    follow_up: {
      needed: true,
      reason: "Prepare premium model with all features for test drive",
      due_at: "2024-01-16T15:00:00Z",
      assignee: "Sarah Mitchell",
    },
    metrics: {
      duration_sec: 510,
      hold_sec: 20,
      silence_sec: 8,
    },
    recording_url: "https://recordings.example.com/call_013.mp3",
    transcript_url: "https://transcripts.example.com/call_013.txt",
    tags: ["hot_lead", "premium_vehicle", "financing_ready", "luxury_upgrade"],
  },
]

// Additional mock data for analytics and dashboard metrics
export const mockAnalyticsData = {
  callVolume: {
    daily: [45, 52, 38, 61, 49, 55, 42],
    weekly: [320, 285, 310, 295, 340, 315, 330],
    monthly: [1250, 1180, 1320, 1280, 1400, 1350],
  },
  conversionRates: {
    sales: 0.68,
    service: 0.82,
    finance: 0.74,
    overall: 0.75,
  },
  customerSatisfaction: {
    current: 4.6,
    previous: 4.4,
    trend: "up",
    responses: 156,
  },
  revenueMetrics: {
    sales: 2850000,
    service: 890000,
    finance: 420000,
    total: 4160000,
    growth: 0.12,
  },
  agentPerformance: [
    {
      name: "Mike Rodriguez",
      calls: 45,
      conversion: 0.78,
      satisfaction: 4.7,
      revenue: 125000,
    },
    {
      name: "Sarah Mitchell",
      calls: 52,
      conversion: 0.82,
      satisfaction: 4.8,
      revenue: 145000,
    },
    {
      name: "Tom Wilson",
      calls: 38,
      conversion: 0.71,
      satisfaction: 4.5,
      revenue: 98000,
    },
    {
      name: "Jennifer Walsh",
      calls: 41,
      conversion: 0.85,
      satisfaction: 4.6,
      revenue: 112000,
    },
    {
      name: "Carlos Martinez",
      calls: 35,
      conversion: 0.79,
      satisfaction: 4.7,
      revenue: 89000,
    },
  ],
  topVehicles: [
    { make: "Honda", model: "Civic", interest: 0.28, testDrives: 45 },
    { make: "Toyota", model: "Camry", interest: 0.25, testDrives: 38 },
    { make: "Ford", model: "F-150", interest: 0.22, testDrives: 32 },
    { make: "Hyundai", model: "Tucson", interest: 0.18, testDrives: 28 },
    { make: "Volkswagen", model: "Jetta", interest: 0.15, testDrives: 25 },
  ],
  serviceMetrics: {
    appointments: 89,
    completed: 76,
    revenue: 89000,
    averageTicket: 1171,
    customerRetention: 0.88,
  },
  salesMetrics: {
    leads: 156,
    testDrives: 89,
    sales: 67,
    conversionRate: 0.43,
    averageSalePrice: 42500,
  },
  followUpTasks: [
    {
      id: "task_001",
      type: "call_back",
      customer: "Manan Chawla",
      vehicle: "2022 Honda Civic EX",
      dueDate: "2024-01-16T14:00:00Z",
      assignee: "Mike Rodriguez",
      priority: "high",
      notes: "Send test drive reminder and prepare financing options",
      status: "pending",
    },
    {
      id: "task_002",
      type: "service_reminder",
      customer: "Robert Chen",
      vehicle: "2018 Toyota Corolla LE",
      dueDate: "2024-01-16T17:00:00Z",
      assignee: "Jennifer Walsh",
      priority: "medium",
      notes: "Send service reminder and prepare diagnostic checklist",
      status: "pending",
    },
    {
      id: "task_003",
      type: "appointment_reminder",
      customer: "Maria Garcia",
      vehicle: "2023 Ford F-150 XLT",
      dueDate: "2024-01-18T13:00:00Z",
      assignee: "Tom Wilson",
      priority: "high",
      notes: "Send reminder 1 hour before appointment and prepare both engine options",
      status: "pending",
    },
    {
      id: "task_004",
      type: "sales_callback",
      customer: "David Thompson",
      vehicle: "2021 VW Golf SE",
      dueDate: "2024-01-15T16:00:00Z",
      assignee: "Sales Manager",
      priority: "urgent",
      notes: "Sales manager callback required for competitive pricing",
      status: "pending",
    },
    {
      id: "task_005",
      type: "service_followup",
      customer: "Anonymous",
      vehicle: "2015 Ford Fusion SE",
      dueDate: "2024-01-18T10:00:00Z",
      assignee: "Service Team",
      priority: "low",
      notes: "Follow-up call to check if customer needs additional parts or service",
      status: "pending",
    },
  ],
  recentActivity: [
    {
      id: "activity_001",
      type: "appointment_scheduled",
      customer: "Lisa Anderson",
      vehicle: "2023 Hyundai Tucson Limited",
      timestamp: "2024-01-15T17:42:15Z",
      agent: "Sarah Mitchell",
      details: "Test drive scheduled for tomorrow morning",
    },
    {
      id: "activity_002",
      type: "service_completed",
      customer: "Michael Brown",
      vehicle: "2019 Toyota Camry XLE",
      timestamp: "2024-01-15T16:30:00Z",
      agent: "Jennifer Walsh",
      details: "Oil change and inspection completed",
    },
    {
      id: "activity_003",
      type: "sale_closed",
      customer: "Lisa Wilson",
      vehicle: "2023 Nissan Altima",
      timestamp: "2024-01-15T16:00:00Z",
      agent: "Mike Rodriguez",
      details: "Vehicle sold with extended warranty",
    },
    {
      id: "activity_004",
      type: "follow_up_scheduled",
      customer: "Jennifer Lee",
      vehicle: "2022 VW Jetta SEL",
      timestamp: "2024-01-15T16:52:15Z",
      agent: "Sales Team",
      details: "Competitive pricing follow-up scheduled",
    },
    {
      id: "activity_005",
      type: "warranty_escalation",
      customer: "Anonymous",
      vehicle: "2016 Ford Fusion Titanium",
      timestamp: "2024-01-15T11:25:40Z",
      agent: "Warranty Specialist",
      details: "Transmission warranty coverage verification needed",
    },
  ],
  customerInsights: {
    demographics: {
      ageGroups: {
        "18-25": 0.12,
        "26-35": 0.28,
        "36-45": 0.32,
        "46-55": 0.18,
        "55+": 0.10,
      },
      incomeLevels: {
        "Under $50K": 0.15,
        "$50K-$75K": 0.25,
        "$75K-$100K": 0.35,
        "$100K-$150K": 0.20,
        "$150K+": 0.05,
      },
    },
    preferences: {
      communicationMethod: {
        phone: 0.45,
        email: 0.35,
        sms: 0.20,
      },
      vehicleTypes: {
        sedan: 0.35,
        suv: 0.40,
        truck: 0.15,
        hybrid: 0.10,
      },
      serviceIntervals: {
        "Every 3 months": 0.25,
        "Every 6 months": 0.45,
        "Annually": 0.20,
        "As needed": 0.10,
      },
    },
    satisfactionDrivers: {
      "Service Quality": 4.7,
      "Communication": 4.5,
      "Timeliness": 4.6,
      "Price": 4.3,
      "Vehicle Selection": 4.8,
    },
  },
  marketTrends: {
    inventory: {
      total: 156,
      new: 89,
      used: 67,
      popularMakes: ["Honda", "Toyota", "Ford", "Hyundai", "Volkswagen"],
    },
    pricing: {
      averageNew: 38500,
      averageUsed: 24500,
      marketTrend: "stable",
      competitivePosition: "competitive",
    },
    demand: {
      trendingUp: ["Hybrids", "SUVs", "Trucks"],
      trendingDown: ["Sedans", "Luxury"],
      seasonalFactors: "winter_prep",
    },
  },
}
